import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Upload,Play,Save}from'lucide-react';
import'./style.css';
declare global{interface Window{studioAPI:any}}
const api=()=>window.studioAPI||{openFile:async()=>[],process:async()=>({ok:false,error:'api_not_ready'}),info:async()=>({ok:false,error:'api_not_ready'}),saveConfig:async()=>({}),loadConfig:async()=>({})};
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function App(){
  const[apiKey,setApiKey]=useState(''); const[styleJson,setStyleJson]=useState(''); const[audioFile,setAudioFile]=useState('');
  const[chunkSeconds,setChunkSeconds]=useState('8'); const[targetPromptCount,setTargetPromptCount]=useState(''); const[originalText,setOriginalText]=useState(''); const[extraRequirement,setExtraRequirement]=useState(''); const[dialog,setDialog]=useState(false); const[subtitles,setSubtitles]=useState(false);
  const[status,setStatus]=useState('Sẵn sàng'); const[result,setResult]=useState<any[]>([]); const[autoInfo,setAutoInfo]=useState<any>(null);
  useEffect(()=>{api().loadConfig().then((c:any)=>{setApiKey(c.apiKeys||c.apiKey||'');setStyleJson(c.styleJson||'')})},[]);
  async function pickAudio(){const r=await api().openFile({properties:['openFile'],filters:[{name:'Audio',extensions:['mp3','wav','m4a']}]});if(r?.[0]){setAudioFile(r[0]); const info=await api().info({file:r[0],chunkSeconds}); if(info?.ok)setAutoInfo(info)}}
  async function save(){await api().saveConfig({apiKeys:apiKey,styleJson});setStatus('Đã lưu cấu hình')}
  async function run(){setStatus('Đang cắt audio, nhận dạng văn bản và tạo prompt...');const r=await api().process({apiKeys:apiKey,styleJson,audioFile,chunkSeconds,targetPromptCount,originalText,extraRequirement,dialog,subtitles});if(r?.prompts)setResult(r.prompts);setStatus(r?.ok?`Hoàn tất: ${r.count} scene • ${r.resultFile}`:`Lỗi: ${r?.error}`)}
  return <div className="app"><aside><h1>Audio Prompt Studio</h1><p>Tool riêng tạo prompt từ audio + văn bản gốc</p><button onClick={save}><Save size={16}/> Lưu cấu hình</button><button onClick={run}><Play size={16}/> Tạo prompt</button></aside><main><section className="card"><h2>Thiết lập</h2><div className="grid"><Field label="Gemini API keys"><textarea className="smallarea" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Mỗi dòng một API key"/></Field><Field label="Cắt audio mỗi giây"><input value={chunkSeconds} onChange={async e=>{const v=e.target.value.replace(new RegExp('[^0-9]','g'),'');setChunkSeconds(v); if(audioFile){const info=await api().info({file:audioFile,chunkSeconds:v}); if(info?.ok)setAutoInfo(info)}}/></Field><Field label="Số prompt tự động"><input readOnly value={targetPromptCount || (autoInfo?.promptCount ? String(autoInfo.promptCount) : '')} placeholder="Tự tính theo thời lượng / giây cắt"/></Field><Field label="Lời thoại"><select value={dialog?'yes':'no'} onChange={e=>setDialog(e.target.value==='yes')}><option value="no">Không</option><option value="yes">Có</option></select></Field><Field label="Phụ đề"><select value={subtitles?'yes':'no'} onChange={e=>setSubtitles(e.target.value==='yes')}><option value="no">Không</option><option value="yes">Có</option></select></Field></div><button className="soft" onClick={pickAudio}><Upload size={16}/> Tải audio mp3 lên</button><p className="hint">Audio: {audioFile||'chưa chọn'}<br/>Thời lượng: {autoInfo?.durationSeconds?Math.round(autoInfo.durationSeconds)+'s':'chưa phân tích'} • Số prompt tự động: {autoInfo?.promptCount||'chưa có'}</p></section><section className="card"><h2>Phong cách JSON</h2><textarea value={styleJson} onChange={e=>setStyleJson(e.target.value)} placeholder="Dán style_analysis JSON ở đây"/></section><section className="card"><h2>Văn bản gốc</h2><textarea value={originalText} onChange={e=>setOriginalText(e.target.value)} placeholder="Dán văn bản gốc để AI so sánh transcript và chỉnh cho chính xác"/></section><section className="card"><h2>Yêu cầu thêm vào prompt</h2><textarea value={extraRequirement} onChange={e=>setExtraRequirement(e.target.value)} placeholder="Ví dụ: prompt ngắn gọn, phong cách điện ảnh, giữ nhân vật đồng nhất, không có chữ trên màn hình..."/></section><section className="card"><h2>Kết quả</h2><p>{status}</p><pre>{JSON.stringify(result,null,2)}</pre></section></main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
